/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfaceBiblioteque;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import rederr.ActionRenderer;


/**
 *
 * @author User
 */
public class InterfaceBibliotecaire extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public InterfaceBibliotecaire() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 800));

        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 800));

        jLabel2.setBackground(new java.awt.Color(175, 94, 94));
        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 3, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(133, 193, 233));
        jLabel2.setText("Bibliotèque Des Élites");

        jPanel2.setBackground(new java.awt.Color(133, 193, 233));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 102, 51), new java.awt.Color(153, 153, 255), new java.awt.Color(204, 204, 255)));
        jPanel2.setForeground(new java.awt.Color(133, 193, 233));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton1.setText("Rechercher");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 204, 255), new java.awt.Color(0, 204, 204)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton2.setText("Ajouter un livre ");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 204, 255), new java.awt.Color(0, 204, 204)));
        jButton2.setName("btnAjoutlivre"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton3.setText("listes des emprunts");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 204, 255), new java.awt.Color(0, 204, 204)));
        jButton3.setName("ListesDesEmprunt"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton4.setText("Modifier");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 204, 255), new java.awt.Color(0, 204, 204)));
        jButton4.setName("ModifierLiVreInfo"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton5.setText("banni un etudiant");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 204, 255), new java.awt.Color(0, 204, 204)));
        jButton5.setName("sanctionnBanir"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(133, 193, 233));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 102, 51), new java.awt.Color(153, 153, 255), new java.awt.Color(204, 204, 255)));
        jPanel3.setForeground(new java.awt.Color(133, 193, 233));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Titre", "Auteur", "Année de publication", "Maison d'édition", "Status", "Date d'emprunt", "Date limite", "Action"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(174, 174, 174))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1403, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             
    // Logique pour rechercher un livre par titre
    String searchTerm = JOptionPane.showInputDialog("Entrez le titre à rechercher:");
    if (searchTerm != null && !searchTerm.trim().isEmpty()) {
        // Créer un modèle temporaire pour afficher les résultats
        DefaultTableModel filteredModel = new DefaultTableModel();
        filteredModel.setColumnIdentifiers(new Object[] {"Titre", "Auteur", "Année", "Maison", "Statut", "Date d'Emprunt", "Date Limite", "Actions"});
            
           JTable tableModel = new JTable();
        
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String titre = tableModel.getValueAt(i, 0).toString().toLowerCase();
            
            // Vérifiez si le titre contient le terme de recherche
            if (titre.contains(searchTerm.toLowerCase())) {
                // Ajouter la ligne correspondante au modèle filtré
                Object[] rowData = new Object[tableModel.getColumnCount()];
                for (int j = 0; j < tableModel.getColumnCount(); j++) {
                    rowData[j] = tableModel.getValueAt(i, j);
                }
                filteredModel.addRow(rowData);
            }
        }
        
        // Vérifiez si des résultats ont été trouvés
        if (filteredModel.getRowCount() > 0) {
            // Afficher les résultats dans le tableau
            jTable1.setModel(filteredModel);
        } else {
            JOptionPane.showMessageDialog(this, "Aucun livre trouvé avec ce titre.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez entrer un titre valide.");
    }

 


// TODO add your handling code here:
        // Logique pour rechercher un livre
    //String searchTerm = JOptionPane.showInputDialog("Entrez le titre ou l'auteur à rechercher:");
    // Ajoutez ici la logique pour rechercher dans le modèle de la table
    // (Vous pouvez filtrer le modèle de la table en fonction de searchTerm)
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        AjouterLivreFrame ajouterLivreFrame = new AjouterLivreFrame(model);
        ajouterLivreFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
       
  
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           // Logique pour afficher la liste des emprunts
    // Exemple d'affichage d'une nouvelle fenêtre
    JFrame empruntFrame = new JFrame("Liste des Emprunts");
    JTable empruntTable = new JTable(); // Remplacez par votre modèle de table approprié
    JScrollPane scrollPane = new JScrollPane(empruntTable);
    
    // Ajouter ici la logique pour peupler empruntTable avec les données appropriées

    empruntFrame.add(scrollPane);
    empruntFrame.setSize(400, 300);
    empruntFrame.setVisible(true);
    empruntFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

// Logique pour afficher la liste des emprunts
    // Par exemple, ouvrir un nouveau cadre ou afficher des informations
    //JOptionPane.showMessageDialog(this, "Affichage de la liste des emprunts...");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // Logique pour modifier les informations d'un livre
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        // Ouvrir un cadre pour modifier les informations
        // Vous pouvez pré-remplir les champs avec les données de la ligne sélectionnée
        JOptionPane.showMessageDialog(this, "Modifier le livre sélectionné...");
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un livre à modifier.");
    }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         // Logique pour bannir un étudiant
    String studentName = JOptionPane.showInputDialog("Entrez le nom de l'étudiant à bannir:");
    // Ajoutez ici la logique pour bannir l'étudiant
    JOptionPane.showMessageDialog(this, "Étudiant " + studentName + " banni.");
    }//GEN-LAST:event_jButton5ActionPerformed
public class AjouterLivreFrame extends JFrame {
    
    private JTextField txtTitre, txtAuteur, txtAnnee, txtMaison, txtStatut, txtDateEmprunt, txtDateLimite;
    private JButton btnValider, btnAnnuler;
    private DefaultTableModel tableModel;
    
    public AjouterLivreFrame(DefaultTableModel model) {
        this.tableModel = model;
        initComponents();
    }
    
    private void initComponents() {
        setTitle("Ajouter un Livre");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setLayout(new GridLayout(0, 2));
        
        // Créer les champs et labels
        txtTitre = new JTextField();
        txtAuteur = new JTextField();
        txtAnnee = new JTextField();
        txtMaison = new JTextField();
        txtStatut = new JTextField();
        txtDateEmprunt = new JTextField();
        txtDateLimite = new JTextField();
        
        add(new JLabel("Titre:"));
        add(txtTitre);
        add(new JLabel("Auteur:"));
        add(txtAuteur);
        add(new JLabel("Année:"));
        add(txtAnnee);
        add(new JLabel("Maison:"));
        add(txtMaison);
        add(new JLabel("Statut:"));
        add(txtStatut);
        add(new JLabel("Date Emprunt:"));
        add(txtDateEmprunt);
        add(new JLabel("Date Limite:"));
        add(txtDateLimite);
        
        // Boutons
        btnValider = new JButton("Valider");
        btnAnnuler = new JButton("Annuler");
        add(btnAnnuler);
        add(btnValider);
        
        // Gérer l'événement du bouton "Valider"
        btnValider.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ajouterLivre();
            }
        });
        
        // Gérer l'événement du bouton "Annuler"
        btnAnnuler.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); // Fermer la fenêtre
            }
        });
    }
    
    private void ajouterLivre() {
        // Récupérer les valeurs des champs
        String titre = txtTitre.getText();
        String auteur = txtAuteur.getText();
        String annee = txtAnnee.getText();
        String maison = txtMaison.getText();
        String statut = txtStatut.getText();
        String dateEmprunt = txtDateEmprunt.getText();
        String dateLimite = txtDateLimite.getText();
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(1, 1, 5, 5));
    


    // Créer les boutons
    JButton btnSanction = new JButton();
    JButton btnSupprimer = new JButton();
    
    
    
    btnSanction.setFont(new java.awt.Font("Verdana", 3, 10));
    btnSanction.setText("Sanction");
    btnSanction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, 
        new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), 
        new java.awt.Color(153, 204, 255), new java.awt.Color(0, 204, 204)));
    btnSanction.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            // Get the selected row index
            
        }
    });

    btnSupprimer.setFont(new java.awt.Font("Verdana", 3, 10));
    btnSupprimer.setText("Supprimer");
    btnSupprimer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, 
        new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), 
        new java.awt.Color(153, 204, 255), new java.awt.Color(0, 204, 204)));
    
    JTable newTable = new JTable(tableModel); // Initialize newTable here
        // ...
    btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            int rowIndex = newTable.getSelectedRow();
            if (rowIndex != -1) {
                // Suppression de la ligne sélectionnée
                tableModel.removeRow(rowIndex);
                JOptionPane.showMessageDialog(null, "Ligne " + (rowIndex + 1) + " supprimée.");
            }
        }
    });
    
    
    panel.add(btnSanction);
    panel.add(btnSupprimer);
    
    
    
    
    
    
    
    
    // Créer une nouvelle instance de la classe ActionRenderer
ActionRenderer actionRenderer = new ActionRenderer(panel);

// Ajouter une nouvelle ligne dans le tableau
tableModel.addRow(new Object[] {titre, auteur, annee, maison, statut, dateEmprunt, dateLimite, actionRenderer});
        // Fermer la fenêtre
        dispose();
    }
    
    public void main(String args[]){
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            
            DefaultTableModel model = new DefaultTableModel(new Object[][]{}, new String[]{"Titre", "Auteur", "Année", "Maison", "Statut", "Date Emprunt", "Date Limite"});
            new AjouterLivreFrame(model).setVisible(true);
        }
    });
}
}


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceBibliotecaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceBibliotecaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceBibliotecaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceBibliotecaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceBibliotecaire().setVisible(true);
            }
        });
    }
private DefaultTableModel tableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
